module.exports = {
	focusAnimationDuration: 0.75,
	collapsible: false,
	directed: true,
	focusZoom: 1,
	freezeAllDragEvents: false,
	highlightDegree: 2,
	highlightOpacity: 0.2,
	linkHighlightBehavior: true,
	maxZoom: 8,
  	minZoom: 0.5,
	initialZoom: 1,
	nodeHighlightBehavior: true,
	panAndZoom: false,
	staticGraph: false,
	staticGraphWithDragAndDrop: false,
	width: window.innerWidth - 450,
	height: window.innerHeight,
	d3: {
		alphaTarget: 0.05,
		gravity: -400,
		linkLength: 300,
		linkStrength: 1,
		disableLinkForce: false,
	},
	node: {
	  color: "#d3d3d3",
	  fontColor: "black",
	  fontSize: 10,
	  fontWeight: "normal",
	  highlightColor: "red",
	  highlightFontSize: 14,
	  highlightFontWeight: "bold",
	  highlightStrokeColor: "red",
	  highlightStrokeWidth: 1.5,
	  labelPosition: "",
	  mouseCursor: "crosshair",
	  opacity: 0.9,
	  renderLabel: false,
	  size: 500,
	  strokeColor: "none",
	  strokeWidth: 1.5,
	  svg: "",
	  symbolType: "circle",
	  viewGenerator: null
	},
	link: {
	  color: "lightgray",
	  fontColor: "black",
	  fontSize: 8,
	  fontWeight: "normal",
	  highlightFontSize: 8,
	  highlightFontWeight: "normal",
	  labelProperty: "label",
	  mouseCursor: "pointer",
	  opacity: 1,
	  renderLabel: false,
	  semanticStrokeWidth: true,
	  strokeWidth: 3,
	  markerHeight: 6,
	  markerWidth: 6,
	  type: "STRAIGHT",
	  selfLinkDirection: "TOP_RIGHT",
	  strokeDasharray: 0,
	  strokeDashoffset: 0,
	  strokeLinecap: "butt"
	}
  };
  